"""
Enum module

This file is autogenerated from api specifications
"""


class UserStatusEnum:
    """Represents the `UserStatusEnum` options as used by Mbed Cloud accounts functionality"""

    ACTIVE = "ACTIVE"
    ENROLLING = "ENROLLING"
    INACTIVE = "INACTIVE"
    INVITED = "INVITED"
    RESET = "RESET"

    values = frozenset(("ACTIVE", "ENROLLING", "INACTIVE", "INVITED", "RESET"))

    def __setattr__(self, name, value):
        raise Exception("enum container values cannot be modified")


class ApiKeyStatusEnum:
    """Represents the `ApiKeyStatusEnum` options as used by Mbed Cloud accounts functionality"""

    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"

    values = frozenset(("ACTIVE", "INACTIVE"))

    def __setattr__(self, name, value):
        raise Exception("enum container values cannot be modified")
