"""
Enum module

This file is autogenerated from api specifications
"""

# Python 2 compatibility
from __future__ import unicode_literals
from builtins import str  # noqa
from builtins import object

from mbed_cloud.sdk.common.enum import BaseEnum


class PolicyGroupOrderEnum(BaseEnum):
    """Represents the `PolicyGroupOrderEnum` options

    as used by Mbed Cloud "accounts" functionality
    """

    ASC = "ASC"
    DESC = "DESC"

    values = frozenset(("ASC", "DESC"))


class UserStatusEnum(BaseEnum):
    """Represents the `UserStatusEnum` options

    as used by Mbed Cloud "accounts" functionality
    """

    ACTIVE = "ACTIVE"
    ENROLLING = "ENROLLING"
    INACTIVE = "INACTIVE"
    INVITED = "INVITED"
    RESET = "RESET"

    values = frozenset(("ACTIVE", "ENROLLING", "INACTIVE", "INVITED", "RESET"))


class UserOrderEnum(BaseEnum):
    """Represents the `UserOrderEnum` options

    as used by Mbed Cloud "accounts" functionality
    """

    ASC = "ASC"
    DESC = "DESC"

    values = frozenset(("ASC", "DESC"))


class MyApiKeyStatusEnum(BaseEnum):
    """Represents the `MyApiKeyStatusEnum` options

    as used by Mbed Cloud "accounts" functionality
    """

    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"

    values = frozenset(("ACTIVE", "INACTIVE"))


class MyApiKeyOrderEnum(BaseEnum):
    """Represents the `MyApiKeyOrderEnum` options

    as used by Mbed Cloud "accounts" functionality
    """

    ASC = "ASC"
    DESC = "DESC"

    values = frozenset(("ASC", "DESC"))


class ApiKeyStatusEnum(BaseEnum):
    """Represents the `ApiKeyStatusEnum` options

    as used by Mbed Cloud "accounts" functionality
    """

    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"

    values = frozenset(("ACTIVE", "INACTIVE"))


class ApiKeyOrderEnum(BaseEnum):
    """Represents the `ApiKeyOrderEnum` options

    as used by Mbed Cloud "accounts" functionality
    """

    ASC = "ASC"
    DESC = "DESC"

    values = frozenset(("ASC", "DESC"))


class MyAccountStatusEnum(BaseEnum):
    """Represents the `MyAccountStatusEnum` options

    as used by Mbed Cloud "accounts" functionality
    """

    ACTIVE = "ACTIVE"
    ENROLLING = "ENROLLING"
    RESTRICTED = "RESTRICTED"
    SUSPENDED = "SUSPENDED"

    values = frozenset(("ACTIVE", "ENROLLING", "RESTRICTED", "SUSPENDED"))


class MyAccountMfaStatusEnum(BaseEnum):
    """Represents the `MyAccountMfaStatusEnum` options

    as used by Mbed Cloud "accounts" functionality
    """

    ENFORCED = "enforced"
    OPTIONAL = "optional"

    values = frozenset(("enforced", "optional"))


class SubtenantAccountStatusEnum(BaseEnum):
    """Represents the `SubtenantAccountStatusEnum` options

    as used by Mbed Cloud "accounts" functionality
    """

    ACTIVE = "ACTIVE"
    ENROLLING = "ENROLLING"
    RESTRICTED = "RESTRICTED"
    SUSPENDED = "SUSPENDED"

    values = frozenset(("ACTIVE", "ENROLLING", "RESTRICTED", "SUSPENDED"))


class SubtenantAccountMfaStatusEnum(BaseEnum):
    """Represents the `SubtenantAccountMfaStatusEnum` options

    as used by Mbed Cloud "accounts" functionality
    """

    ENFORCED = "enforced"
    OPTIONAL = "optional"

    values = frozenset(("enforced", "optional"))


class SubtenantAccountOrderEnum(BaseEnum):
    """Represents the `SubtenantAccountOrderEnum` options

    as used by Mbed Cloud "accounts" functionality
    """

    ASC = "ASC"
    DESC = "DESC"

    values = frozenset(("ASC", "DESC"))
