# coding: utf-8

"""
    IAM Identities REST API

    REST API to manage accounts, groups, users and API keys

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class UserInfoResp(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, status=None, username=None, email_verified=False, account_id=None, password_changed_time=None, groups=None, created_at=None, object=None, is_gtc_accepted=False, email=None, is_marketing_accepted=False, etag=None, full_name=None, address=None, creation_time_millis=None, creation_time=None, password=None, phone_number=None, id=None, last_login_time=None):
        """
        UserInfoResp - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'status': 'str',
            'username': 'str',
            'email_verified': 'bool',
            'account_id': 'str',
            'password_changed_time': 'int',
            'groups': 'list[str]',
            'created_at': 'str',
            'object': 'str',
            'is_gtc_accepted': 'bool',
            'email': 'str',
            'is_marketing_accepted': 'bool',
            'etag': 'str',
            'full_name': 'str',
            'address': 'str',
            'creation_time_millis': 'int',
            'creation_time': 'int',
            'password': 'str',
            'phone_number': 'str',
            'id': 'str',
            'last_login_time': 'int'
        }

        self.attribute_map = {
            'status': 'status',
            'username': 'username',
            'email_verified': 'email_verified',
            'account_id': 'account_id',
            'password_changed_time': 'password_changed_time',
            'groups': 'groups',
            'created_at': 'created_at',
            'object': 'object',
            'is_gtc_accepted': 'is_gtc_accepted',
            'email': 'email',
            'is_marketing_accepted': 'is_marketing_accepted',
            'etag': 'etag',
            'full_name': 'full_name',
            'address': 'address',
            'creation_time_millis': 'creationTimeMillis',
            'creation_time': 'creation_time',
            'password': 'password',
            'phone_number': 'phone_number',
            'id': 'id',
            'last_login_time': 'last_login_time'
        }

        self._status = status
        self._username = username
        self._email_verified = email_verified
        self._account_id = account_id
        self._password_changed_time = password_changed_time
        self._groups = groups
        self._created_at = created_at
        self._object = object
        self._is_gtc_accepted = is_gtc_accepted
        self._email = email
        self._is_marketing_accepted = is_marketing_accepted
        self._etag = etag
        self._full_name = full_name
        self._address = address
        self._creation_time_millis = creation_time_millis
        self._creation_time = creation_time
        self._password = password
        self._phone_number = phone_number
        self._id = id
        self._last_login_time = last_login_time

    @property
    def status(self):
        """
        Gets the status of this UserInfoResp.
        The status of the user. INVITED means that the user has not accepted the invitation request. RESET means that the password must be changed immediately.

        :return: The status of this UserInfoResp.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this UserInfoResp.
        The status of the user. INVITED means that the user has not accepted the invitation request. RESET means that the password must be changed immediately.

        :param status: The status of this UserInfoResp.
        :type: str
        """
        allowed_values = ["INVITED", "ACTIVE", "RESET", "INACTIVE"]
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def username(self):
        """
        Gets the username of this UserInfoResp.
        A username containing alphanumerical letters and -,._@+= characters.

        :return: The username of this UserInfoResp.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """
        Sets the username of this UserInfoResp.
        A username containing alphanumerical letters and -,._@+= characters.

        :param username: The username of this UserInfoResp.
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")

        self._username = username

    @property
    def email_verified(self):
        """
        Gets the email_verified of this UserInfoResp.
        A flag indicating whether the user's email address has been verified or not.

        :return: The email_verified of this UserInfoResp.
        :rtype: bool
        """
        return self._email_verified

    @email_verified.setter
    def email_verified(self, email_verified):
        """
        Sets the email_verified of this UserInfoResp.
        A flag indicating whether the user's email address has been verified or not.

        :param email_verified: The email_verified of this UserInfoResp.
        :type: bool
        """

        self._email_verified = email_verified

    @property
    def account_id(self):
        """
        Gets the account_id of this UserInfoResp.
        The UUID of the account.

        :return: The account_id of this UserInfoResp.
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """
        Sets the account_id of this UserInfoResp.
        The UUID of the account.

        :param account_id: The account_id of this UserInfoResp.
        :type: str
        """
        if account_id is None:
            raise ValueError("Invalid value for `account_id`, must not be `None`")

        self._account_id = account_id

    @property
    def password_changed_time(self):
        """
        Gets the password_changed_time of this UserInfoResp.
        A timestamp of the latest change of the user password, in milliseconds.

        :return: The password_changed_time of this UserInfoResp.
        :rtype: int
        """
        return self._password_changed_time

    @password_changed_time.setter
    def password_changed_time(self, password_changed_time):
        """
        Sets the password_changed_time of this UserInfoResp.
        A timestamp of the latest change of the user password, in milliseconds.

        :param password_changed_time: The password_changed_time of this UserInfoResp.
        :type: int
        """

        self._password_changed_time = password_changed_time

    @property
    def groups(self):
        """
        Gets the groups of this UserInfoResp.
        A list of IDs of the groups this user belongs to.

        :return: The groups of this UserInfoResp.
        :rtype: list[str]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """
        Sets the groups of this UserInfoResp.
        A list of IDs of the groups this user belongs to.

        :param groups: The groups of this UserInfoResp.
        :type: list[str]
        """

        self._groups = groups

    @property
    def created_at(self):
        """
        Gets the created_at of this UserInfoResp.
        Creation UTC time RFC3339.

        :return: The created_at of this UserInfoResp.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """
        Sets the created_at of this UserInfoResp.
        Creation UTC time RFC3339.

        :param created_at: The created_at of this UserInfoResp.
        :type: str
        """

        self._created_at = created_at

    @property
    def object(self):
        """
        Gets the object of this UserInfoResp.
        Entity name: always 'user'

        :return: The object of this UserInfoResp.
        :rtype: str
        """
        return self._object

    @object.setter
    def object(self, object):
        """
        Sets the object of this UserInfoResp.
        Entity name: always 'user'

        :param object: The object of this UserInfoResp.
        :type: str
        """
        allowed_values = ["user", "api_key", "group", "account", "account_template", "ca_cert", "list", "error"]
        if object not in allowed_values:
            raise ValueError(
                "Invalid value for `object` ({0}), must be one of {1}"
                .format(object, allowed_values)
            )

        self._object = object

    @property
    def is_gtc_accepted(self):
        """
        Gets the is_gtc_accepted of this UserInfoResp.
        A flag indicating that the General Terms and Conditions has been accepted.

        :return: The is_gtc_accepted of this UserInfoResp.
        :rtype: bool
        """
        return self._is_gtc_accepted

    @is_gtc_accepted.setter
    def is_gtc_accepted(self, is_gtc_accepted):
        """
        Sets the is_gtc_accepted of this UserInfoResp.
        A flag indicating that the General Terms and Conditions has been accepted.

        :param is_gtc_accepted: The is_gtc_accepted of this UserInfoResp.
        :type: bool
        """

        self._is_gtc_accepted = is_gtc_accepted

    @property
    def email(self):
        """
        Gets the email of this UserInfoResp.
        The email address.

        :return: The email of this UserInfoResp.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this UserInfoResp.
        The email address.

        :param email: The email of this UserInfoResp.
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")

        self._email = email

    @property
    def is_marketing_accepted(self):
        """
        Gets the is_marketing_accepted of this UserInfoResp.
        A flag indicating that receiving marketing information has been accepted.

        :return: The is_marketing_accepted of this UserInfoResp.
        :rtype: bool
        """
        return self._is_marketing_accepted

    @is_marketing_accepted.setter
    def is_marketing_accepted(self, is_marketing_accepted):
        """
        Sets the is_marketing_accepted of this UserInfoResp.
        A flag indicating that receiving marketing information has been accepted.

        :param is_marketing_accepted: The is_marketing_accepted of this UserInfoResp.
        :type: bool
        """

        self._is_marketing_accepted = is_marketing_accepted

    @property
    def etag(self):
        """
        Gets the etag of this UserInfoResp.
        API resource entity version.

        :return: The etag of this UserInfoResp.
        :rtype: str
        """
        return self._etag

    @etag.setter
    def etag(self, etag):
        """
        Sets the etag of this UserInfoResp.
        API resource entity version.

        :param etag: The etag of this UserInfoResp.
        :type: str
        """
        if etag is None:
            raise ValueError("Invalid value for `etag`, must not be `None`")

        self._etag = etag

    @property
    def full_name(self):
        """
        Gets the full_name of this UserInfoResp.
        The full name of the user.

        :return: The full_name of this UserInfoResp.
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """
        Sets the full_name of this UserInfoResp.
        The full name of the user.

        :param full_name: The full_name of this UserInfoResp.
        :type: str
        """

        self._full_name = full_name

    @property
    def address(self):
        """
        Gets the address of this UserInfoResp.
        Address.

        :return: The address of this UserInfoResp.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """
        Sets the address of this UserInfoResp.
        Address.

        :param address: The address of this UserInfoResp.
        :type: str
        """

        self._address = address

    @property
    def creation_time_millis(self):
        """
        Gets the creation_time_millis of this UserInfoResp.

        :return: The creation_time_millis of this UserInfoResp.
        :rtype: int
        """
        return self._creation_time_millis

    @creation_time_millis.setter
    def creation_time_millis(self, creation_time_millis):
        """
        Sets the creation_time_millis of this UserInfoResp.

        :param creation_time_millis: The creation_time_millis of this UserInfoResp.
        :type: int
        """

        self._creation_time_millis = creation_time_millis

    @property
    def creation_time(self):
        """
        Gets the creation_time of this UserInfoResp.
        A timestamp of the user creation in the storage, in milliseconds.

        :return: The creation_time of this UserInfoResp.
        :rtype: int
        """
        return self._creation_time

    @creation_time.setter
    def creation_time(self, creation_time):
        """
        Sets the creation_time of this UserInfoResp.
        A timestamp of the user creation in the storage, in milliseconds.

        :param creation_time: The creation_time of this UserInfoResp.
        :type: int
        """

        self._creation_time = creation_time

    @property
    def password(self):
        """
        Gets the password of this UserInfoResp.
        The password when creating a new user. It will will generated when not present in the request.

        :return: The password of this UserInfoResp.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """
        Sets the password of this UserInfoResp.
        The password when creating a new user. It will will generated when not present in the request.

        :param password: The password of this UserInfoResp.
        :type: str
        """

        self._password = password

    @property
    def phone_number(self):
        """
        Gets the phone_number of this UserInfoResp.
        Phone number.

        :return: The phone_number of this UserInfoResp.
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """
        Sets the phone_number of this UserInfoResp.
        Phone number.

        :param phone_number: The phone_number of this UserInfoResp.
        :type: str
        """

        self._phone_number = phone_number

    @property
    def id(self):
        """
        Gets the id of this UserInfoResp.
        The UUID of the user.

        :return: The id of this UserInfoResp.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this UserInfoResp.
        The UUID of the user.

        :param id: The id of this UserInfoResp.
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def last_login_time(self):
        """
        Gets the last_login_time of this UserInfoResp.
        A timestamp of the latest login of the user, in milliseconds.

        :return: The last_login_time of this UserInfoResp.
        :rtype: int
        """
        return self._last_login_time

    @last_login_time.setter
    def last_login_time(self, last_login_time):
        """
        Sets the last_login_time of this UserInfoResp.
        A timestamp of the latest login of the user, in milliseconds.

        :param last_login_time: The last_login_time of this UserInfoResp.
        :type: int
        """

        self._last_login_time = last_login_time

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, UserInfoResp):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
