# coding: utf-8

"""
    Update Service API

    This is the API Documentation for the mbed deployment service which is part of the update service.

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ManifestContentsPayloadInfoPayload(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, integrated=None, reference=None):
        """
        ManifestContentsPayloadInfoPayload - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'integrated': 'str',
            'reference': 'ManifestContentsPayloadInfoPayloadReference'
        }

        self.attribute_map = {
            'integrated': 'integrated',
            'reference': 'reference'
        }

        self._integrated = integrated
        self._reference = reference

    @property
    def integrated(self):
        """
        Gets the integrated of this ManifestContentsPayloadInfoPayload.

        :return: The integrated of this ManifestContentsPayloadInfoPayload.
        :rtype: str
        """
        return self._integrated

    @integrated.setter
    def integrated(self, integrated):
        """
        Sets the integrated of this ManifestContentsPayloadInfoPayload.

        :param integrated: The integrated of this ManifestContentsPayloadInfoPayload.
        :type: str
        """

        self._integrated = integrated

    @property
    def reference(self):
        """
        Gets the reference of this ManifestContentsPayloadInfoPayload.

        :return: The reference of this ManifestContentsPayloadInfoPayload.
        :rtype: ManifestContentsPayloadInfoPayloadReference
        """
        return self._reference

    @reference.setter
    def reference(self, reference):
        """
        Sets the reference of this ManifestContentsPayloadInfoPayload.

        :param reference: The reference of this ManifestContentsPayloadInfoPayload.
        :type: ManifestContentsPayloadInfoPayloadReference
        """

        self._reference = reference

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ManifestContentsPayloadInfoPayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
